### ISSUE TITLE
Small change needed in TTVFast.c to output correct RVs (Kat Deck + Lauren Weiss)

### ISSUE THREAD

**Issue by sealauren** [mindriot101/ttvfast-python#13]
/* Calculate RV if necessary */

    if(j <RV_count){
      RVTime = Time+dt2;
    
      while(RVTime>(RV_struct+j)->time && RVTime-dt<(RV_struct+j)->time){ /* LMW 2016 Nov: This conditional has been updated from "if" --> "while" to account for multiple RV measurements in a single time step */
	if(RVTime-(RV_struct+j)->time > (RV_struct+j)->time-(RVTime-dt)){
	  copy_system(p_tmp,p_RV);
	  new_dt= (RV_struct+j)->time-(RVTime-dt);
	  A(p_RV,new_dt);
	  velocity = compute_RV(p_RV);
	  (RV_struct+j)->RV =velocity;
	  
	}else{
	  copy_system(p,p_RV);
	  new_dt= (RV_struct+j)->time-RVTime;
	  A(p_RV,new_dt);
	  velocity = compute_RV(p_RV);
	  (RV_struct+j)->RV =velocity;
	}
	j++;
      }
    }

**Comment by simonrw** [comment]
Thanks for this, I've released v0.2.1 of `ttvfast` which includes this change.

**Comment by sealauren** [comment]
Thanks so much!  How do I update ttvfast-python to respect the new change in TTVFast.c?  I tried rerunning 
python setup.py install
but that didn’t work.

Thanks!

**Comment by simonrw** [comment]
@sealauren are you installing from inside the git repository? If so you should be able do to:

``` sh
git pull
git submodule update
python setup.py install
```

Otherwise if installing from pypi you should be able to do:

``` sh
pip install -U ttvfast
```

In fact that should work even when installing from the git repository.

>  I tried rerunning python setup.py install but that didn’t work.

In what way didn't it work?

**Comment by sealauren** [comment]
I don’t know how to get around this git error:

$ git submodule update
fatal: Unable to create '/Users/lweiss/ttvfast-python/.git/modules/external/TTVFast/index.lock': Permission denied
Unable to checkout 'ea62714f31f1f32563d45114c49736c1c2c6eff2' in submodule path 'external/TTVFast’

I did the pip install, but somehow when I call ttvfast.ttvfast() from python, it is using the old version of TTVFast.c.  How does it find TTVFast.c?

**Comment by simonrw** [comment]
> $ git submodule update
> fatal: Unable to create '/Users/lweiss/ttvfast-python/.git/modules/external/TTVFast/index.lock': Permission denied
> Unable to checkout 'ea62714f31f1f32563d45114c49736c1c2c6eff2' in submodule path 'external/TTVFast’

Can you find out what the permissions are on the `/Users/lweiss/ttvfast-python/.git/modules/external/TTVFast` directory and the `/Users/lweiss/ttvfast-python/.git/modules/external/TTVFast/index.lock` file, and see if they are the same user as you?

You can try deleting both the checked out directory and module directory and updating again:

``` sh
rm -r external/TTVFast
rm -r .git/modules/external/TTVFast
git submodule init
git submodule update
```

This should clone a fresh copy. You may get the same permissions errors when trying to delete the directories, in which case as I said above work out which user/group owns the index.lock file.

I don't know for sure, but I don't think this file should not exist - I don't have one anywhere in my repository. `.lock` files typically exist to prevent simultaneous writing to a single file. It's possible there was a failed checkout or git command, or perhaps it was interrupted, and this left this file behind.

> I did the pip install, but somehow when I call ttvfast.ttvfast() from python, it is using the old version of TTVFast.c.  How does it find TTVFast.c?

I'm not sure about this. I've just released a new version on pypi v0.2.2. Can you try installing with `pip install --upgrade ttvfast` and dump the output here. The `--upgrade` is important as it won't do anything if it's already installed, even an older version. If you then run the following python commands:

``` python
import ttvfast
print(ttvfast.__version__)
```

If it prints "0.2.2" then it includes the latest changes. If it prints anything else, or raises an exception then you have an old version. If you still have a problem with 0.2.2 then I need to have a deeper think. That code definitely includes your change.

If you try all of the things I've suggested and it still doesn't work, could you send me a program that tests the new changes so I can do some debugging for myself?

**Comment by sealauren** [comment]
Hi Simon,

I have managed to get to a point where I cannot call ttvfast from within python at all.  Here is what I did:
1. I deleted my ttvfast-python repo, downloaded a fresh version, and downloaded the TTVFast module with these commands:

git clone https://github.com/mindriot101/ttvfast-python.git
cd ttvfast-python
git submodule init
git submodule update # grabs code from TTVFast
2. I created a new branch, lw, in both ttvfast and in c_version, and checked it out.
3. From the ttvfast-python directroy, I ran

python setup.py install

Output:
unicorn:ttvfast-python lweiss$ python setup.py install
running install
running bdist_egg
running egg_info
creating ttvfast.egg-info
writing ttvfast.egg-info/PKG-INFO
writing top-level names to ttvfast.egg-info/top_level.txt
writing dependency_links to ttvfast.egg-info/dependency_links.txt
writing manifest file 'ttvfast.egg-info/SOURCES.txt'
reading manifest file 'ttvfast.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ttvfast.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.6-x86_64-2.7
creating build/lib.macosx-10.6-x86_64-2.7/ttvfast
copying ttvfast/**init**.py -> build/lib.macosx-10.6-x86_64-2.7/ttvfast
copying ttvfast/models.py -> build/lib.macosx-10.6-x86_64-2.7/ttvfast
copying ttvfast/version.py -> build/lib.macosx-10.6-x86_64-2.7/ttvfast
running build_ext
building 'ttvfast._ttvfast' extension
creating build/temp.macosx-10.6-x86_64-2.7
creating build/temp.macosx-10.6-x86_64-2.7/src
creating build/temp.macosx-10.6-x86_64-2.7/external
creating build/temp.macosx-10.6-x86_64-2.7/external/TTVFast
creating build/temp.macosx-10.6-x86_64-2.7/external/TTVFast/c_version
gcc -fno-strict-aliasing -I/Users/lweiss/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iexternal/TTVFast/c_version -I/Users/lweiss/anaconda/include/python2.7 -c src/ttvfast_wrapper.c -o build/temp.macosx-10.6-x86_64-2.7/src/ttvfast_wrapper.o -std=c99
gcc -fno-strict-aliasing -I/Users/lweiss/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iexternal/TTVFast/c_version -I/Users/lweiss/anaconda/include/python2.7 -c external/TTVFast/c_version/TTVFast.c -o build/temp.macosx-10.6-x86_64-2.7/external/TTVFast/c_version/TTVFast.o -std=c99
In file included from external/TTVFast/c_version/TTVFast.c:53:0:
external/TTVFast/c_version/machine-epsilon.c:2:8: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 double determine_machine_epsilon()
        ^~~~~~~~~~~~~~~~~~~~~~~~~

external/TTVFast/c_version/TTVFast.c: In function ‘read_helio_cartesian_params’:
external/TTVFast/c_version/TTVFast.c:392:17: warning: variable ‘u’ set but not used [-Wunused-but-set-variable]
   double a,r,vs,u;
                 ^

gcc -bundle -undefined dynamic_lookup -L/Users/lweiss/anaconda/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.6-x86_64-2.7/src/ttvfast_wrapper.o build/temp.macosx-10.6-x86_64-2.7/external/TTVFast/c_version/TTVFast.o -L/Users/lweiss/anaconda/lib -o build/lib.macosx-10.6-x86_64-2.7/ttvfast/_ttvfast.so
creating build/bdist.macosx-10.6-x86_64
creating build/bdist.macosx-10.6-x86_64/egg
creating build/bdist.macosx-10.6-x86_64/egg/ttvfast
copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/__init__.py -> build/bdist.macosx-10.6-x86_64/egg/ttvfast
copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/_ttvfast.so -> build/bdist.macosx-10.6-x86_64/egg/ttvfast
copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/models.py -> build/bdist.macosx-10.6-x86_64/egg/ttvfast
copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/version.py -> build/bdist.macosx-10.6-x86_64/egg/ttvfast
byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/__init__.py to **init**.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/models.py to models.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/version.py to version.pyc
creating stub loader for ttvfast/_ttvfast.so
byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/_ttvfast.py to _ttvfast.pyc
creating build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying ttvfast.egg-info/PKG-INFO -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying ttvfast.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying ttvfast.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying ttvfast.egg-info/top_level.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.6-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg' and adding 'build/bdist.macosx-10.6-x86_64/egg' to it
removing 'build/bdist.macosx-10.6-x86_64/egg' (and everything under it)
Processing ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg
Copying ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg to /Users/lweiss/anaconda/lib/python2.7/site-packages
Removing ttvfast 0.0.4 from easy-install.pth file
Adding ttvfast 0.2.2 to easy-install.pth file
1. Then I ran py.test, and got the following error:

unicorn:ttvfast-python lweiss$ py.test
Traceback (most recent call last):
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/_pytest/config.py", line 543, in importconftest
    mod = conftestpath.pyimport()
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/py/_path/local.py", line 641, in pyimport
    __import__(modname)
  File "/Users/lweiss/ttvfast-python/testing/conftest.py", line 2, in <module>
    from ttvfast import models
  File "/Users/lweiss/ttvfast-python/ttvfast/**init**.py", line 5, in <module>
    from ._ttvfast import _ttvfast as _ttvfast_fn
ImportError: No module named _ttvfast
ERROR: could not load /Users/lweiss/ttvfast-python/testing/conftest.py
1. As a hail-Mary, I tried installing from pip:

unicorn:~ lweiss$ pip install ttvfast-python
Collecting ttvfast-python
  Could not find a version that satisfies the requirement ttvfast-python (from versions: )
No matching distribution found for ttvfast-python

Do you have any idea what’s going on?  I recently upgraded to macOS 10.12.1, and I am afraid that might be at the root of my problems.

**Comment by simonrw** [comment]
Sorry I'm not at my computer this weekend, but the package is ttvfast
not ttvfast-python: https://pypi.python.org/pypi/ttvfast

Can you try installing that?

**Comment by simonrw** [comment]
Ok I think I understand what's going on.

> 1. I deleted my ttvfast-python repo, downloaded a fresh version, and downloaded the TTVFast module with these commands:
> 
> git clone https://github.com/mindriot101/ttvfast-python.git
> cd ttvfast-python
> git submodule init
> git submodule update # grabs code from TTVFast
> 1. I created a new branch, lw, in both ttvfast and in c_version, and
>    checked it out.
> 2. From the ttvfast-python directroy, I ran
> 
> python setup.py install
> 
> Output:
> unicorn:ttvfast-python lweiss$ python setup.py install
> running install
> running bdist_egg
> running egg_info
> creating ttvfast.egg-info
> writing ttvfast.egg-info/PKG-INFO
> writing top-level names to ttvfast.egg-info/top_level.txt
> writing dependency_links to ttvfast.egg-info/dependency_links.txt
> writing manifest file 'ttvfast.egg-info/SOURCES.txt'
> reading manifest file 'ttvfast.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'ttvfast.egg-info/SOURCES.txt'
> installing library code to build/bdist.macosx-10.6-x86_64/egg
> running install_lib
> running build_py
> creating build
> creating build/lib.macosx-10.6-x86_64-2.7
> creating build/lib.macosx-10.6-x86_64-2.7/ttvfast
> copying ttvfast/**init**.py -> build/lib.macosx-10.6-x86_64-2.7/ttvfast
> copying ttvfast/models.py -> build/lib.macosx-10.6-x86_64-2.7/ttvfast
> copying ttvfast/version.py -> build/lib.macosx-10.6-x86_64-2.7/ttvfast
> running build_ext
> building 'ttvfast._ttvfast' extension
> creating build/temp.macosx-10.6-x86_64-2.7
> creating build/temp.macosx-10.6-x86_64-2.7/src
> creating build/temp.macosx-10.6-x86_64-2.7/external
> creating build/temp.macosx-10.6-x86_64-2.7/external/TTVFast
> creating build/temp.macosx-10.6-x86_64-2.7/external/TTVFast/c_version
> gcc -fno-strict-aliasing -I/Users/lweiss/anaconda/include -arch x86_64
> -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
> -Iexternal/TTVFast/c_version -I/Users/lweiss/anaconda/include/python2.7
> -c src/ttvfast_wrapper.c -o
> build/temp.macosx-10.6-x86_64-2.7/src/ttvfast_wrapper.o -std=c99
> gcc -fno-strict-aliasing -I/Users/lweiss/anaconda/include -arch x86_64
> -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
> -Iexternal/TTVFast/c_version -I/Users/lweiss/anaconda/include/python2.7
> -c external/TTVFast/c_version/TTVFast.c -o
> build/temp.macosx-10.6-x86_64-2.7/external/TTVFast/c_version/TTVFast.o
> -std=c99
> In file included from external/TTVFast/c_version/TTVFast.c:53:0:
> external/TTVFast/c_version/machine-epsilon.c:2:8: warning: function
> declaration isn’t a prototype [-Wstrict-prototypes]
>  double determine_machine_epsilon()
>         ^~~~~~~~~~~~~~~~~~~~~~~~~
> 
> external/TTVFast/c_version/TTVFast.c: In function
> ‘read_helio_cartesian_params’:
> external/TTVFast/c_version/TTVFast.c:392:17: warning: variable ‘u’ set
> but not used [-Wunused-but-set-variable]
>    double a,r,vs,u;
>                  ^
> 
> gcc -bundle -undefined dynamic_lookup -L/Users/lweiss/anaconda/lib -arch
> x86_64 -arch x86_64
> build/temp.macosx-10.6-x86_64-2.7/src/ttvfast_wrapper.o
> build/temp.macosx-10.6-x86_64-2.7/external/TTVFast/c_version/TTVFast.o
> -L/Users/lweiss/anaconda/lib -o
> build/lib.macosx-10.6-x86_64-2.7/ttvfast/_ttvfast.so
> creating build/bdist.macosx-10.6-x86_64
> creating build/bdist.macosx-10.6-x86_64/egg
> creating build/bdist.macosx-10.6-x86_64/egg/ttvfast
> copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/__init__.py ->
> build/bdist.macosx-10.6-x86_64/egg/ttvfast
> copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/_ttvfast.so ->
> build/bdist.macosx-10.6-x86_64/egg/ttvfast
> copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/models.py ->
> build/bdist.macosx-10.6-x86_64/egg/ttvfast
> copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/version.py ->
> build/bdist.macosx-10.6-x86_64/egg/ttvfast
> byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/__init__.py to
> **init**.pyc
> byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/models.py to
> models.pyc
> byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/version.py to
> version.pyc
> creating stub loader for ttvfast/_ttvfast.so
> byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/_ttvfast.py to
> _ttvfast.pyc
> creating build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
> copying ttvfast.egg-info/PKG-INFO ->
> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
> copying ttvfast.egg-info/SOURCES.txt ->
> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
> copying ttvfast.egg-info/dependency_links.txt ->
> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
> copying ttvfast.egg-info/top_level.txt ->
> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
> writing build/bdist.macosx-10.6-x86_64/egg/EGG-INFO/native_libs.txt
> zip_safe flag not set; analyzing archive contents...
> creating dist
> creating 'dist/ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg' and adding
> 'build/bdist.macosx-10.6-x86_64/egg' to it
> removing 'build/bdist.macosx-10.6-x86_64/egg' (and everything under it)
> Processing ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg
> Copying ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg to
> /Users/lweiss/anaconda/lib/python2.7/site-packages
> Removing ttvfast 0.0.4 from easy-install.pth file
> Adding ttvfast 0.2.2 to easy-install.pth file

This sounds like it installed ok.

> 1. Then I ran py.test, and got the following error:
> 
> unicorn:ttvfast-python lweiss$ py.test
> Traceback (most recent call last):
>   File
>   "/Users/lweiss/anaconda/lib/python2.7/site-packages/_pytest/config.py",
>   line 543, in importconftest
>     mod = conftestpath.pyimport()
>   File
>   "/Users/lweiss/anaconda/lib/python2.7/site-packages/py/_path/local.py",
>   line 641, in pyimport
>     __import__(modname)
>   File "/Users/lweiss/ttvfast-python/testing/conftest.py", line 2, in
>   <module>
>     from ttvfast import models
>   File "/Users/lweiss/ttvfast-python/ttvfast/**init**.py", line 5, in
>   <module>
>     from ._ttvfast import _ttvfast as _ttvfast_fn
> ImportError: No module named _ttvfast
> ERROR: could not load /Users/lweiss/ttvfast-python/testing/conftest.py

I think this is because when you ran the tests, it looked for the first `ttvfast` module it could find, which is the one in the current directory which hasn't been "installed" as such. When python builds a module it puts the compiled code under `build`. When py.test tried importing it, it picked the `ttvfast` directory in the current path which does not include `_ttvfast.so`. If you change directory to somewhere else and try running

``` python
import ttvfast`
```

it will probably work, provided the python you run is the same that you ran `setup.py install` with. If you want to run the tests, you have to run:

``` sh
python setup.py develop
```

or

``` sh
pip install -e .
```

and you will find the file `ttvfast/_ttvfast.so` should now exist. In which case the tests should run ok.

> 1. As a hail-Mary, I tried installing from pip:
> 
> unicorn:~ lweiss$ pip install ttvfast-python
> Collecting ttvfast-python
>   Could not find a version that satisfies the requirement ttvfast-python
>   (from versions: )
> No matching distribution found for ttvfast-python

As I said in my previous response, the package is called `ttvfast`.

Sorry I can't be much more of a help.

**Comment by sealauren** [comment]
Thanks so much Simon!

**Comment by simonrw** [comment]
@sealauren do I take it that this fixed your problem?!

**Comment by sealauren** [comment]
No not yet. I'll try to do some more digging around.

**Comment by sealauren** [comment]
Hi Simon,

I’m still getting the problem that python cannot find ._ttvfast.  Here is the error message:

## In [1]: import ttvfast

ImportError                               Traceback (most recent call last)
<ipython-input-1-bbdcab7c8dd2> in <module>()
----> 1 import ttvfast

/Users/lweiss/ttvfast-python/ttvfast/**init**.py in <module>()
      3 "Fast TTV computation"
      4 
----> 5 from ._ttvfast import _ttvfast as _ttvfast_fn
      6 from . import models
      7 from .version import __version__

ImportError: No module named _ttvfast

I notice that I have a file in ttvfast called ._ttvfast.pyi, but nothing called ._ttvfast.py.

I tried re-running setup.py (and pip), and here was the output:

unicorn:ttvfast-python lweiss$ python setup.py install
running install
running bdist_egg
running egg_info
writing ttvfast.egg-info/PKG-INFO
writing top-level names to ttvfast.egg-info/top_level.txt
writing dependency_links to ttvfast.egg-info/dependency_links.txt
reading manifest file 'ttvfast.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ttvfast.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.macosx-10.6-x86_64/egg
creating build/bdist.macosx-10.6-x86_64/egg/ttvfast
copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/**init**.py -> build/bdist.macosx-10.6-x86_64/egg/ttvfast
copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/_ttvfast.so -> build/bdist.macosx-10.6-x86_64/egg/ttvfast
copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/models.py -> build/bdist.macosx-10.6-x86_64/egg/ttvfast
copying build/lib.macosx-10.6-x86_64-2.7/ttvfast/version.py -> build/bdist.macosx-10.6-x86_64/egg/ttvfast
byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/__init__.py to **init**.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/models.py to models.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/version.py to version.pyc
creating stub loader for ttvfast/_ttvfast.so
byte-compiling build/bdist.macosx-10.6-x86_64/egg/ttvfast/_ttvfast.py to _ttvfast.pyc
creating build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying ttvfast.egg-info/PKG-INFO -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying ttvfast.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying ttvfast.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying ttvfast.egg-info/top_level.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.6-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg' and adding 'build/bdist.macosx-10.6-x86_64/egg' to it
removing 'build/bdist.macosx-10.6-x86_64/egg' (and everything under it)
Processing ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg
Removing /Users/lweiss/anaconda/lib/python2.7/site-packages/ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg
Copying ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg to /Users/lweiss/anaconda/lib/python2.7/site-packages
ttvfast 0.2.2 is already the active version in easy-install.pth

Installed /Users/lweiss/anaconda/lib/python2.7/site-packages/ttvfast-0.2.2-py2.7-macosx-10.6-x86_64.egg
Processing dependencies for ttvfast==0.2.2
Finished processing dependencies for ttvfast==0.2.2
unicorn:ttvfast-python lweiss$ pip install ttvfast
Requirement already satisfied: ttvfast in /Users/lweiss/ttvfast-python

Lauren M. Weiss, PhD
Trottier Postdoctoral Fellow
Institute for Research on Exoplanets
Univeristé de Montréal
lauren@astro.umontreal.ca

**Comment by sealauren** [comment]
Hi Simon,

I figured it out, it was a problem in my path.  All fixed!  Thanks for your help updating TTVFast.c.

Best wishes,

Lauren M. Weiss, PhD
Trottier Postdoctoral Fellow
Institute for Research on Exoplanets
Univeristé de Montréal
lauren@astro.umontreal.ca

**Comment by simonrw** [comment]
@sealauren awesome, thanks for making the package better! Closing this issue
